spring.application.name=spring-keycloak
server.port=8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/social-network-realm
jwt.auth.converter.resource-id=social-network-backend
jwt.auth.converter.principal-attribute-name=preferred_username

# postgres db
spring.datasource.url=jdbc:postgresql://localhost:5432/keycloak_spring_auth
spring.datasource.username=osama
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# spring security
token.signing.key="123456abcdef"